export const extensionToName = {
    ag: 'Angular',
    ts: 'TypeScript',
    js: 'JavaScript',
    jsx: 'JavaScript (JSX)',
    html: 'HTML',
    css: 'CSS',
    md: 'Markdown',
    json: 'JSON',
    toml: 'TOML',
    vue: 'Vue',
    py: 'Python',
    java: 'Java',
    cpp: 'C++',
    rb: 'Ruby',
    php: 'PHP',
    go: 'Go',
    swift: 'Swift',
    kotlin: 'Kotlin',
    rs: 'Rust',
    tsx: 'TypeScript (TSX)',
    sh: 'Shell Script',
    yaml: 'YAML',
    xml: 'XML',
    sql: 'SQL',
    r: 'R',
    perl: 'Perl',
    c: 'C',
    h: 'Header file',
    pl: 'Perl',
    cs: 'C#',
    vb: 'Visual Basic',
    lua: 'Lua',
    scala: 'Scala',
    groovy: 'Groovy',
    dart: 'Dart',
    clj: 'Clojure',
    jl: 'Julia',
    erl: 'Erlang',
    elixir: 'Elixir',
    haml: 'Haml',
    pug: 'Pug',
    coffee: 'CoffeeScript',
    sass: 'Sass',
    less: 'Less',
    styl: 'Stylus',
    scss: 'SCSS',
    tf: 'Terraform',
    tfvars: 'Terraform variables',
    hcl: 'HashiCorp Configuration Language (HCL)',
    yml: 'YAML',
    csv: 'Comma-separated values (CSV)',
    tsv: 'Tab-separated values (TSV)',
    ini: 'INI file',
    conf: 'Configuration file',
    cfg: 'Configuration file',
    log: 'Log file',
    txt: 'Text file',
    doc: 'Microsoft Word document',
    docx: 'Microsoft Word document (modern)',
    xls: 'Microsoft Excel spreadsheet',
    xlsx: 'Microsoft Excel spreadsheet (modern)',
    ppt: 'Microsoft PowerPoint presentation',
    pptx: 'Microsoft PowerPoint presentation (modern)',
    pdf: 'PDF document',
    jpg: 'JPEG image',
    jpeg: 'JPEG image',
    png: 'PNG image',
    gif: 'GIF image',
    bmp: 'Bitmap image',
    tiff: 'TIFF image',
    svg: 'Scalable Vector Graphics (SVG)',
    mp3: 'MP3 audio',
    wav: 'WAV audio',
    ogg: 'Ogg Vorbis audio',
    mp4: 'MP4 video',
    avi: 'AVI video',
    mkv: 'Matroska video',
    mov: 'QuickTime video',
    zip: 'ZIP archive',
    rar: 'RAR archive',
    tar: 'Tar archive',
    gz: 'Gzip archive',
    bz2: 'Bzip2 archive',
    dmg: 'Disk Image',
    exe: 'Executable file',
    bat: 'Batch file',
    cmd: 'Windows Command Prompt script',
    ps1: 'PowerShell script',
    jar: 'Java Archive (JAR)',
    war: 'Web Archive (WAR)',
    ear: 'Enterprise Archive (EAR)',
    dll: 'Dynamic Link Library (DLL)',
    lib: 'Library file',
    obj: 'Object file',
    pdb: 'Program Database (PDB)',
    bak: 'Backup file',
    temp: 'Temporary file',
    bak: 'Backup file',
    temp: 'Temporary file',
};
