export const extensionToName = {
    ag: 'Angular',
    ts: 'TypeScript',
    js: 'JavaScript',
    jsx: 'JSX',
    html: 'HTML',
    css: 'CSS',
    md: 'Markdown',
    json: 'JSON',
    toml: 'TOML',
    vue: 'Vue',
    py: 'Python',
    java: 'Java',
    cpp: 'C++',
    rb: 'Ruby',
    php: 'PHP',
    go: 'Go',
    swift: 'Swift',
    kotlin: 'Kotlin',
    rs: 'Rust',
    tsx: 'TSX',
    sh: 'Shell',
    yaml: 'YAML',
    xml: 'XML',
    sql: 'SQL',
    r: 'R',
    perl: 'Perl',
    c: 'C',
    h: 'Header',
    pl: 'Perl',
    cs: 'C#',
    vb: 'VB',
    lua: 'Lua',
    scala: 'Scala',
    groovy: 'Groovy',
    dart: 'Dart',
    clj: 'Clojure',
    jl: 'Julia',
    erl: 'Erlang',
    elixir: 'Elixir',
    haml: 'Haml',
    pug: 'Pug',
    coffee: 'Coffee',
    sass: 'Sass',
    less: 'Less',
    styl: 'Stylus',
    scss: 'SCSS',
    tf: 'Terraform',
    tfvars: 'TF vars',
    hcl: 'HCL',
    yml: 'YAML',
    csv: 'CSV',
    tsv: 'TSV',
    ini: 'INI file',
    conf: 'Config',
    cfg: 'Config',
    log: 'Log file',
    txt: 'Text file',
    doc: 'Word',
    docx: 'Word',
    xls: 'Excel',
    xlsx: 'Excel',
    ppt: 'PPT',
    pptx: 'PPT',
    pdf: 'PDF',
    jpg: 'JPEG',
    jpeg: 'JPEG',
    png: 'PNG',
    gif: 'GIF',
    bmp: 'Bitmap',
    tiff: 'TIFF',
    svg: 'SVG',
    mp3: 'MP3',
    wav: 'WAV',
    ogg: 'Ogg',
    mp4: 'MP4',
    avi: 'AVI',
    mkv: 'MKV',
    mov: 'MOV',
    zip: 'ZIP',
    rar: 'RAR',
    tar: 'Tar',
    gz: 'Gzip',
    bz2: 'Bzip2',
    dmg: 'Disk',
    exe: 'Exe',
    bat: 'Batch',
    cmd: 'CMD',
    ps1: 'PS',
    jar: 'Java',
    war: 'WAR',
    ear: 'EAR',
    dll: 'DLL',
    lib: 'Library',
    obj: 'Object',
    pdb: 'PDB',
    bak: 'Backup',
    temp: 'Temp',
    pbxproj: 'Pbxproj',
};

export const extensionToExclude = {
    lock: true,
    min: true,
    map: true,
    gz: true,
    br: true,
    bz2: true,
    xz: true,
    zst: true,
    json: true,
    yaml: true,
    license: true,
    pbxproj: true,
};

export function capitalizeFirstLetter(string) {
    if (!string) return string;
    return string.charAt(0).toUpperCase() + string.slice(1);
}
